VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 1  'vbSimpleBound
  DataSourceBehavior  = 1  'vbDataSource
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "game2"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"No"
Attribute VB_Ext_KEY = "Member0" ,"game2"
Public Sub collo_Timer()
End Sub

Public Sub colli()
End Sub

Public Sub jiop_KeyDown(KeyCode As Integer, Shift As Integer)
End Sub

Public Sub obst_Timer()
End Sub

Public Sub Timer1_Timer()
End Sub

Public Sub obstaclegen()
End Sub

Public Sub Timer12_Timer()
End Sub

Public Sub Timer13_Timer()
End Sub

Public Sub Timer3_Timer()
End Sub

Public Sub charstate2()
End Sub

Public Sub charstate1()
End Sub

Public Sub Timer4_Timer()
End Sub

Public Sub Timer5_Timer()
End Sub

Public Sub Timer6_Timer()
End Sub

Public Sub Timer7_Timer()
End Sub

Public Sub backmov()
End Sub

Public Sub changeback()
End Sub

Public Sub level2()
End Sub

Public Sub Timer8_Timer()
End Sub

Public Sub obsp()
End Sub

